export const photosData = [
  {
    id: 1,
    category: "ventanas",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 2,
    category: "puertas",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet salo consecteturquam enim iste.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 3,
    category: "mamparas",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur atem omnis te.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 4,
    category: "mosquiteros",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 5,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 6,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 7,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit,tutur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 8,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 9,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, titi consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 10,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet tata consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 11,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 12,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 13,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 14,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
  {
    id: 15,
    category: "muebles",
    date: "Janvier 2020",
    infos: "Lorem ipsum dolor sit, amet consectetur adipisosamm ente.",
    img: "./assets/img/projet-2.jpg",
  },
];
