export const photosData = [
  {
    id: 1,
    category: "ventana",
    línea: "Módena",
    producto: "producto",
    infos: "corredizas 2 hojas DVH + paño fijo",
    img: "https://i.ibb.co/Dz5Mdqb/IMG-20240315-WA0005.jpg",
  },
  {
    id: 2,
    category: "puerta",
    línea: "Módena",
    producto: "producto",
    infos: "puerta módena negra ciega",
    img: "https://i.ibb.co/vHDqs80/IMG-20240807-WA0004.jpg",
  },
  {
    id: 3,
    category: "puerta",
    línea: "Módena",
    producto: "producto",
    infos: "puerta módena blanca con vidrio",
    img: "https://i.ibb.co/XyxjdJD/IMG-20240807-WA0011.jpg",
  },
  {
    id: 4,
    category: "ventana",
    línea: "Módena",
    producto: "producto",
    infos: "corredizas 2 hojas DVH",
    img: "https://i.ibb.co/5krtPWQ/IMG-20240807-WA0013.jpg",
  },
  {
    id: 5,
    category: "puerta",
    línea: "Módena",
    producto: "producto",
    infos: "puerta módena blanca con vidrio",
    img: "https://i.ibb.co/VtcxsX9/IMG-20240807-WA0012.jpg",
  },
  {
    id: 6,
    category: "ventana",
    línea: "Módena",
    producto: "producto",
    infos: "ventiluz DVH + paño fijo",
    img: "https://i.ibb.co/5GghmTm/IMG-20240315-WA0015.jpg",
  },
  {
    id: 7,
    category: "ventana",
    línea: "Módena",
    producto: "producto",
    infos: "corredizas 3 hojas DVH + paño fijo",
    img: "https://i.ibb.co/Yyn3MTh/IMG-20240315-WA0003.jpg",
  },
  {
    id: 8,
    category: "ventana",
    línea: "Módena",
    producto: "producto",
    infos: "corredizas DVH y banderola DVH",
    img: "https://i.ibb.co/x6bL3Bj/ventana-resize.jpg",
  },
  {
    id: 9,
    category: "otro",
    línea: "Módena",
    producto: "obra",
    infos: "divisiones en DVH",
    img: "https://i.ibb.co/4ggLqv3/IMG-20240204-WA0002.jpg",
  },
  {
    id: 10,
    category: "ventana",
    línea: "Módena",
    producto: "obra",
    infos: "ventana DVH",
    img: "https://i.ibb.co/yh9SPfc/IMG-20240204-WA0012.jpg",
  },
  {
    id: 11,
    category: "ventana",
    línea: "Módena",
    producto: "obra",
    infos: "corredizas + paño fijo en DVH",
    img: "https://i.ibb.co/jMhF822/IMG-20240204-WA0015.jpg",
  },
  {
    id: 12,
    category: "puerta",
    línea: "Módena",
    producto: "obra",
    infos: "puerta + paños fijos en DVH",
    img: "https://i.ibb.co/wdbVDLK/fenetre-porte.jpg",
  },
  {
    id: 13,
    category: "puerta",
    línea: "Módena",
    producto: "obra",
    infos: "puerta + anti chorro en DVH",
    img: "https://i.ibb.co/bJRp594/porte-fenetre-rz.jpg",
  },
  {
    id: 14,
    category: "ventana",
    línea: "Módena",
    producto: "obra",
    infos: "corredizas 2 hojas + paños fijos DVH",
    img: "https://i.ibb.co/nsL60ZB/IMG-20240808-WA0009.jpg",
  },
  {
    id: 15,
    category: "otro",
    línea: "Módena",
    producto: "obra",
    infos: "divisiones todo DVH con melamina",
    img: "https://i.ibb.co/9wgqTzF/IMG-20240807-WA0017.jpg",
  },
  {
    id: 16,
    category: "ventana",
    línea: "Módena",
    producto: "obra",
    infos: "corredizas 3 hojas + paño fijo DVH",
    img: "https://i.ibb.co/3fKK9Xn/IMG-20240807-WA0001.jpg",
  },
  {
    id: 17,
    category: "ventana",
    línea: "Módena",
    producto: "obra",
    infos: "divisiones corredizas + paños fijos DVH",
    img: "https://i.ibb.co/10nTqcK/Whats-App-Image-2024-08-08-11-33-05-3e4a87c5.jpg",
  },
  {
    id: 18,
    category: "puerta",
    línea: "Herrero",
    producto: "producto",
    infos: "puertas herrero con vidrio 4mm + mosquitero",
    img: "  https://i.ibb.co/6D2jfTq/puertas-resize.jpg",
  },
  {
    id: 19,
    category: "otro",
    línea: "Módena",
    producto: "obra",
    infos: "divisiones aluminio con melamina",
    img: "https://i.ibb.co/Bzrrq0c/IMG-20240204-WA0006.jpg",
  },
  {
    id: 20,
    category: "puerta",
    línea: "Módena",
    producto: "obra",
    infos: "puerta con vidrio DVH",
    img: "https://i.ibb.co/WBLjJpB/IMG-20240204-WA0001.jpg",
  },
];
